
name: Deploy App

on:
  workflow_dispatch:
    inputs:
        app:
          description: 'Applications to build'
          required: true
          type: choice
          options:
            - docs
            - playground
        strategy:
          description: 'Build strategy'
          required: true
          type: choice
          options:
            - workflow
            - script
          default: workflow


jobs:
  build-workflow:
    if: ${{ github.event.inputs.strategy == 'workflow' }}
    uses: ./.github/workflows/build-app/action.yml
    with:
      app: ${{ github.event.inputs.app }}
  build-script:
    if: ${{ github.event.inputs.strategy == 'script' }}
    uses: ./.github/workflows/build-app-root/action.yml
    with:
      app: ${{ github.event.inputs.app }}

    
